### PR TITLE
Fake CC Gen

### PR DESCRIPTION
**Pull request by dankor33**
Fake CC Gen

### CODE REVIEW

**Comment by TheCuteOwl** [comment]
Cannot add it! It uses external package, and I wont use another package

**Comment by dankor33** [comment]
> Cannot add it! It uses external package, and I wont use another package

Oh ok sorry for the bother

**Comment by TheCuteOwl** [comment]
It was a good idea, just i dont want to add another external package

**Comment by dankor33** [comment]
Yea am might make it gen just using the luhn algorithm

**Pull request closed without merging**
